SELECT
	'YOUNGEST' AS TYPE,
	worker.`NAME`, 
	worker.BIRTHDAY
FROM
	worker
WHERE BIRTHDAY = (SELECT MAX(BIRTHDAY) FROM worker)
UNION
SELECT
	'ELDEST' AS TYPE,
	worker.`NAME`, 
	worker.BIRTHDAY
FROM
	worker
WHERE BIRTHDAY = (SELECT MIN(BIRTHDAY) FROM worker)
