SELECT
	CONCAT('Project ',project.ID) AS NAME, 
	DATEDIFF(FINISH_DATE,START_DATE) DIV 30 AS MONTH_COUNT
FROM
	project
WHERE
	DATEDIFF(FINISH_DATE,START_DATE) DIV 30 = (SELECT MAX(DATEDIFF(FINISH_DATE,START_DATE) DIV 30) FROM project)

	 